### ISSUE TITLE
Missing dependency: Levenshtein

### ISSUE THREAD

**Issue by edmcman** [PeiweiHu/DeGPT#2]

**Comment by PeiweiHu** [comment]
Hi, thanks for your comments! I think `pip install python-levenshtein` can solve this issue.

**Comment by edmcman** [comment]
Yes, I was able to figure it out fairly quickly.  But you have a list of other requirements in the README.md, so I thought you might like to add it there!

**Comment by PeiweiHu** [comment]
Totally agree. I will provide a more detailed README (containing your helpful advice) and a better version with neat code in May.
